### ISSUE TITLE
Issue with a-star algrithom

### ISSUE THREAD

**Issue by zhaobenx** [SebLague/Pathfinding#4]
https://github.com/SebLague/Pathfinding/blob/b938872d12bbf9a78cda1e88cbb6a5acff25ccbf/Episode%2004%20-%20heap/Assets/Scripts/Pathfinding.cs#L45

Referring to [Wikipedia](https://en.wikipedia.org/wiki/A*_search_algorithm), there, hCost( Wiki call it fScore) should be the sum of distance and gCost.

I didn't compile your script, but I implemented it in Python, and in the beginning, I always find something wrong. After I changed it in the Wiki's way, it worked.

**Comment by SebLague** [comment]
The hCost IS the distance (in this case using manhattan dst instead of euclidean). If you look in the Node class you'll see there is an 'fCost' property which returns hCost + gCost. My implementation is in line with the wiki.

**Comment by zhaobenx** [comment]
Oh thanks！
