### ISSUE TITLE
Occasional sub-optimal paths returned

### ISSUE THREAD

**Issue by Reousa** [SebLague/Pathfinding#9]
Implementation returns sub-optimal paths in rare occasions.

Example:
The path to the right side is sub-optimal.
![img1](https://media.discordapp.net/attachments/340229922960179204/664660355833921547/unknown.png)

This is due to the implementation skipping neighbor nodes in the closedSet without checking their comparative gCost to the currently opened cell's selected neighbor, resulting in a neighbor with a higher cost occasionally being selected.

Code illustration & proposed fix:
Starting at line 44 in episode 4
```csharp
				foreach (Node neighbour in grid.GetNeighbours(currentNode)) {
					if (!neighbour.walkable || closedSet.Contains(neighbour)) {
						continue;
					}
					
					int newMovementCostToNeighbour = currentNode.gCost + GetDistance(currentNode, neighbour);
					if (newMovementCostToNeighbour < neighbour.gCost || !openSet.Contains(neighbour)) {
```

Fix:

```csharp
				foreach (Node neighbour in grid.GetNeighbours(currentNode)) {
					if (!neighbour.walkable || (closedSet.Contains(neighbour) && newMovementCostToNeighbour >= neighbour.gCost)) {
						continue;
					}
					
					int newMovementCostToNeighbour = currentNode.gCost + GetDistance(currentNode, neighbour);
					if (newMovementCostToNeighbour < neighbour.gCost || !openSet.Contains(neighbour)) {
```

**Comment by PeterBengtson** [comment]
Your fix uses the value of newMovementCostToNeighbour before it is declared. Is this code really correct?

**Comment by Reousa** [comment]
I declare it at the start of the foreach loop as I have a slightly differen implementation:

```csharp
					foreach (Cell neighbour in mapGrid.GetNeighbours(currentCell))
					{
						int newMovementCostToNeighbour = currentCell.gCost + GetDistance(currentCell, neighbour);

						if (neighbour.cellTypeRaw == (byte)CellType.Unwalkable || (closedSet.Contains(neighbour) && newMovementCostToNeighbour >= neighbour.gCost))
						{
							continue;
						}

						if (newMovementCostToNeighbour < neighbour.gCost || !openSet.Contains(neighbour))
						{
							neighbour.gCost = newMovementCostToNeighbour;
							neighbour.hCost = GetDistance(neighbour, targetCell);
							neighbour.parent = currentCell;

							if (!openSet.Contains(neighbour))
								openSet.Add(neighbour);
							else
								openSet.UpdateItem(neighbour);
						}
					}
```

Though after debugging further & calculating by hand it turned out this wasn't the real issue (even though adding the check had fixed it, it came up elsewhere later), but rather another modification I made to the implementation.

For reference, there's no reason to use this check in Sebastian's implementation. This repo works perfectly fine as-is.

Appologies for not clarifying prior to closing. :)
